#!/usr/bin/env bash
set -euo pipefail

mode=${1:-}
rom=${2:-}
[[ ${mode} == smoke || ${mode} == long || ${mode} == recovery ]] || {
    echo "usage: $0 smoke|long|recovery /absolute/path/to/bublbobl.rom" >&2
    exit 2
}
[[ ${rom} == /* && -f ${rom} ]] || {
    echo "ROM must be an existing absolute file path" >&2
    exit 2
}
[[ ${rom,,} == *.rom ]] || {
    echo "The determinism target requires an assembled .rom; assemble ZIP/directory inputs privately with jtframe mra2rom first." >&2
    exit 2
}
command -v docker >/dev/null || {
    echo "docker is required for the supported JOTEGO Verilator environment" >&2
    exit 2
}

repo=$(git rev-parse --show-toplevel)
private_root=${PRIVATE_ARTIFACT_ROOT:-}
[[ ${private_root} == /* ]] || {
    echo "PRIVATE_ARTIFACT_ROOT must be an absolute path outside Git" >&2
    exit 2
}
case ${private_root}/ in
    "${repo}/"*)
        echo "PRIVATE_ARTIFACT_ROOT must be outside the Git worktree" >&2
        exit 2
        ;;
esac

rom_size=$(stat -c %s "${rom}")
rom_md5=$(md5sum "${rom}" | awk '{print $1}')
rom_sha256=$(sha256sum "${rom}" | awk '{print $1}')
rom_crc32=$(python3 -c 'import pathlib,sys,zlib; data=pathlib.Path(sys.argv[1]).read_bytes(); print(f"{zlib.crc32(data)&0xffffffff:08x}")' "${rom}")

# This is the assembled bublbobl (Japan Ver 0.1) image generated by the
# repository's current public MRA. Refuse accidental variants before simulation.
[[ ${rom_size} == 786692 && ${rom_md5} == fcbcd7500f6a7421e827373cfa8890d3 ]] || {
    echo "Unsupported assembled ROM: size=${rom_size}, md5=${rom_md5}" >&2
    echo "Expected bublbobl Japan Ver 0.1: size=786692, md5=fcbcd7500f6a7421e827373cfa8890d3" >&2
    exit 2
}

case ${mode} in
    smoke)
        frames=${LINK2P_SMOKE_FRAMES:-600}
        patterns=(scripted)
        reset_delay=
        ;;
    long)
        frames=${LINK2P_LONG_FRAMES:-10000}
        patterns=(neutral scripted scripted_alt)
        # A second common reset-release timing, after the ROM download, tests
        # that determinism is not an artifact of the default release instant.
        reset_delay=100
        ;;
    recovery)
        frames=${LINK2P_RECOVERY_FRAMES:-2400}
        patterns=(scripted)
        reset_delay=
        runtime_reset_frame=${LINK2P_RUNTIME_RESET_FRAME:-1300}
        runtime_reset_hold_ms=${LINK2P_RUNTIME_RESET_HOLD_MS:-200}
        ;;
esac
[[ ${frames} =~ ^[1-9][0-9]*$ ]] || {
    echo "frame count must be a positive integer" >&2
    exit 2
}
if [[ ${mode} == recovery ]]; then
    [[ ${runtime_reset_frame} =~ ^[1-9][0-9]*$ &&
       ${runtime_reset_hold_ms} =~ ^[1-9][0-9]*$ ]] || {
        echo "runtime reset frame and hold must be positive integers" >&2
        exit 2
    }
    (( runtime_reset_frame < frames )) || {
        echo "runtime reset frame must occur before the requested final frame" >&2
        exit 2
    }
fi
verilator_threads=${LINK2P_VERILATOR_THREADS:-2}
[[ ${verilator_threads} =~ ^[1-9][0-9]*$ ]] || {
    echo "LINK2P_VERILATOR_THREADS must be a positive integer" >&2
    exit 2
}

commit=$(git rev-parse --short=12 HEAD)
artifact_base=${private_root}/JTBUBL-Link2P/simulation/determinism
mkdir -p "${artifact_base}"
run_root=$(mktemp -d "${artifact_base}/${mode}-${commit}-XXXXXX")

cp --reflink=auto "${rom}" "${run_root}/rom.bin"
# The simulation BRAM model reads the MCU region separately. In the assembled
# image it begins after the four-byte header at MCU_START (0xB8000).
dd if="${rom}" of="${run_root}/mcu.bin" bs=1 skip=$((0xB8004)) count=4096 status=none
chmod a-w "${run_root}/rom.bin" "${run_root}/mcu.bin"

python3 "${repo}/scripts/link2p/prepare-jtbubl-dual.py" \
    --jtframe "${repo}/modules/jtframe" --out "${run_root}"
for pattern in "${patterns[@]}"; do
    mkdir -p "${run_root}/${pattern}"
done

container_work=/jtcores/cores/bubl/ver/link2p-determinism
simulation_frames=${frames}
if [[ -n ${reset_delay} ]]; then
    # MAXFRAME is measured from ROM-download completion, while CRC evidence is
    # intentionally suppressed until the delayed common reset is released.
    # Leave ample terminal frames so the evidence still contains >=10,000.
    simulation_frames=$((frames + 60))
fi
jtsim_args=(-verilator -load -dipsw ffff -video "${simulation_frames}" -fast -batch)
if [[ -n ${reset_delay} ]]; then
    jtsim_args+=(-d "LINK2P_RESET_HOLD_MS=${reset_delay}")
fi
if [[ ${mode} == recovery ]]; then
    simulation_frames=$((frames + 60))
    jtsim_args=(-verilator -load -dipsw ffff -video "${simulation_frames}" -fast -batch
        -d "LINK2P_RUNTIME_RESET_FRAME=${runtime_reset_frame}"
        -d "LINK2P_RUNTIME_RESET_HOLD_MS=${runtime_reset_hold_ms}")
fi

printf 'ROM accepted: size=%s crc32=%s sha256=%s md5=%s\n' \
    "${rom_size}" "${rom_crc32}" "${rom_sha256}" "${rom_md5}"
printf 'Private dual-instance run: %s (%s frames; patterns: %s)\n' \
    "${run_root}" "${frames}" "${patterns[*]}"

docker run --rm \
    -v "${repo}:/jtcores" \
    -v "${run_root}:${container_work}" \
    -w "${container_work}" \
    -e "LINK2P_VERILATOR_THREADS=${verilator_threads}" \
    jotego/linter -lc '
        set -eo pipefail
        git config --global --add safe.directory /jtcores
        sim_args=("$@")
        set --
        source /jtcores/setprj.sh >/dev/null
        set -- "${sim_args[@]}"
        set -u
        jtsim "$@" -keepcpp keep -showcmd
        verilator \
            -I$CORES/bubl/hdl -I$JTFRAME/hdl/inc \
            -I$MODULES/jtkcpu/hdl -I$MODULES/jt900h/hdl \
            --timescale 1ps/1ps \
            game_test_single.v \
            /jtcores/scripts/link2p/verilator/link2p_dual_game_test.sv \
            $JTFRAME/hdl/video/jtframe_lfbuf*.v \
            $JTFRAME/hdl/ver/psram128.v \
            -f core.def -f filtered.f \
            -Wno-TIMESCALEMOD --timescale-override 1ns/1ps -Wno-fatal \
            -o sim --quiet-stats --threads "$LINK2P_VERILATOR_THREADS" --prefix UUT --assert \
            --cc --exe test.cpp sdram.cpp wavewritter.cpp cabinet.cpp \
            cheats.cpp sim_utils.cpp -Wwarn-UNDRIVEN \
            --waiver-output waiver --top-module game_test
        make -j -C obj_dir -f UUT.mk sim \
            OPT_FAST="-O3 -march=native" \
            OPT_SLOW="-O3 -march=native" \
            OPT_GLOBAL="-O3 -march=native"
    ' link2p-sim "${jtsim_args[@]}" 2>&1 | tee "${run_root}/build.log"

# Each run gets its own writable simulation directory/state. Only immutable ROM
# and generated microcode files are linked from the common compiled-model root.
shopt -s nullglob
support_files=("${run_root}/rom.bin" "${run_root}/mcu.bin" "${run_root}"/*.uc "${run_root}"/*.vh "${run_root}"/*.hex "${run_root}"/*.mem)
shopt -u nullglob
for pattern in "${patterns[@]}"; do
    for support in "${support_files[@]}"; do
        ln -s "../$(basename "${support}")" "${run_root}/${pattern}/$(basename "${support}")"
    done
done

run_pids=()
run_containers=()
run_token=$(basename "${run_root}" | tr '[:upper:]' '[:lower:]')
cleanup_run_children() {
    local container pid
    for container in "${run_containers[@]}"; do
        docker stop --timeout 5 "${container}" >/dev/null 2>&1 || true
    done
    for pid in "${run_pids[@]}"; do
        kill "${pid}" >/dev/null 2>&1 || true
    done
    wait >/dev/null 2>&1 || true
}
trap 'cleanup_run_children; exit 130' INT TERM
trap cleanup_run_children EXIT
for pattern in "${patterns[@]}"; do
    printf 'Starting %s input pattern...\n' "${pattern}"
    container_name=link2p-${run_token}-${pattern}
    run_containers+=("${container_name}")
    docker run --rm \
        --name "${container_name}" \
        -v "${repo}:/jtcores:ro" \
        -v "${run_root}:${container_work}" \
        -w "${container_work}/${pattern}" \
        jotego/linter -lc '
            set -e
            mkdir frames
            ../obj_dir/sim --inputs "$1" --video-limit -time 1
        ' link2p-sim "/jtcores/scripts/link2p/verilator/${pattern}.cab" \
        2>&1 | tee "${run_root}/${pattern}/run.log" &
    run_pids+=("$!")
done

run_failed=0
for index in "${!run_pids[@]}"; do
    if wait "${run_pids[$index]}"; then
        printf 'Completed %s input pattern.\n' "${patterns[$index]}"
    else
        printf 'FAILED %s input pattern; see its private run.log.\n' "${patterns[$index]}" >&2
        run_failed=1
    fi
done
(( run_failed == 0 )) || exit 1
trap - INT TERM EXIT

for pattern in "${patterns[@]}"; do
    crc_a=${run_root}/${pattern}/frames/a.crc
    crc_b=${run_root}/${pattern}/frames/b.crc
    [[ -s ${crc_a} && -s ${crc_b} ]] || {
        echo "missing frame CRC stream for ${pattern}" >&2
        exit 1
    }
    cmp "${crc_a}" "${crc_b}"
    count_a=$(wc -l < "${crc_a}")
    count_b=$(wc -l < "${crc_b}")
    (( count_a >= frames && count_b >= frames )) || {
        echo "short CRC stream for ${pattern}: A=${count_a} B=${count_b}, expected at least ${frames}" >&2
        exit 1
    }
    distinct=$(sort -u "${crc_a}" | wc -l)
    if (( frames >= 600 && distinct < 2 )); then
        echo "frozen video CRC stream for ${pattern}: only ${distinct} distinct frame CRC" >&2
        exit 1
    fi
    stream_sha=$(sha256sum "${crc_a}" | awk '{print $1}')
    printf '%s frames=%s a=%s b=%s distinct=%s crc_stream_sha256=%s PASS\n' \
        "${pattern}" "${frames}" "${count_a}" "${count_b}" "${distinct}" "${stream_sha}" \
        | tee "${run_root}/${pattern}/result.txt"
done

{
    printf 'mode=%s\n' "${mode}"
    printf 'requested_frames=%s\n' "${frames}"
    printf 'simulator_frame_limit=%s\n' "${simulation_frames}"
    printf 'patterns=%s\n' "${patterns[*]}"
    printf 'post_download_reset_hold_ms=%s\n' "${reset_delay:-0}"
    printf 'runtime_reset_frame=%s\n' "${runtime_reset_frame:-0}"
    printf 'runtime_reset_hold_ms=%s\n' "${runtime_reset_hold_ms:-0}"
    printf 'verilator_threads=%s\n' "${verilator_threads}"
    printf 'rom_size=%s\n' "${rom_size}"
    printf 'rom_crc32=%s\n' "${rom_crc32}"
    printf 'rom_md5=%s\n' "${rom_md5}"
    printf 'rom_sha256=%s\n' "${rom_sha256}"
    printf 'jtcores_commit=%s\n' "$(git rev-parse HEAD)"
    printf 'pocket_commit=%s\n' "$(git -C modules/jtframe/target/pocket rev-parse HEAD)"
    printf 'dip_switches=ffff\n'
    printf 'result=PASS\n'
} > "${run_root}/result.txt"

echo "Dual-JTBUBL ${mode} determinism PASS: ${run_root}"
